version: '3'
services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
  task3:
    image: mindal/task3
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres: {}