spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-alfa-kafka
      auto-offset-reset: earliest
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
