spring:
  kafka:
    bootstrap-servers: 130.193.48.164:29092
    consumer:
      group-id: bogdanov.task2.31
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin