/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.alfa.bogdanov.task1.controller;

//@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-27T13:06:39.963Z")
//
//@Api(value = "atms", description = "the atms API")
//@RequestMapping(value = "")
//public interface AtmsApi {
//
//    @ApiOperation(value = "getById", nickname = "getByIdUsingGET", notes = "", response = AtmResponse.class, tags={ "atm-controller", })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "OK", response = AtmResponse.class),
//        @ApiResponse(code = 404, message = "NOT FOUND", response = ErrorResponse.class) })
//    @RequestMapping(value = "/atms/{id}",
//        produces = { "*/*" },
//        method = RequestMethod.GET)
//    ResponseEntity<AtmResponse> getByIdUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Integer id);
//
//
//    @ApiOperation(value = "getNearestAtm", nickname = "getNearestAtmUsingGET", notes = "", response = AtmResponse.class, tags={ "atm-controller", })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "OK", response = AtmResponse.class) })
//    @RequestMapping(value = "/atms/nearest",
//        produces = { "*/*" },
//        method = RequestMethod.GET)
//    ResponseEntity<AtmResponse> getNearestAtmUsingGET(@ApiParam(value = "latitude") @Valid @RequestParam(value = "latitude", required = false) String latitude,@ApiParam(value = "longitude") @Valid @RequestParam(value = "longitude", required = false) String longitude,@ApiParam(value = "payments", defaultValue = "false") @Valid @RequestParam(value = "payments", required = false, defaultValue="false") Boolean payments);
//
//
//    @ApiOperation(value = "getNearestAtmsWithMoney", nickname = "getNearestAtmsWithMoneyUsingGET", notes = "", response = AtmResponse.class, responseContainer = "List", tags={ "atm-controller", })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "OK", response = AtmResponse.class, responseContainer = "List") })
//    @RequestMapping(value = "/atms/nearest-with-alfik",
//        produces = { "*/*" },
//        method = RequestMethod.GET)
//    ResponseEntity<List<AtmResponse>> getNearestAtmsWithMoneyUsingGET(@ApiParam(value = "alfik") @Valid @RequestParam(value = "alfik", required = false) Integer alfik,@ApiParam(value = "latitude") @Valid @RequestParam(value = "latitude", required = false) String latitude,@ApiParam(value = "longitude") @Valid @RequestParam(value = "longitude", required = false) String longitude);
//
//}
